packages:
  - apps/*
  - packages/*

catalog:
  '@orpc/client': 1.12.2
  '@orpc/openapi': 1.12.2
  '@orpc/server': 1.12.2
  '@orpc/zod': 1.12.2
  '@types/node': 22.13.14
  better-auth: 1.4.9
  dotenv: 17.2.2
  typescript: "5"
  zod: 4.1.13

onlyBuiltDependencies:
  - simple-git-hooks
