packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': 2.3.13
  '@orpc/client': 1.13.4
  '@orpc/openapi': 1.13.4
  '@orpc/server': 1.13.4
  '@orpc/tanstack-query': 1.13.4
  '@orpc/zod': 1.13.4
  '@tailwindcss/vite': 4.1.18
  '@tanstack/react-query': 5.90.20
  '@types/node': 25.1.0
  '@types/react': 19.2.10
  '@types/react-dom': 19.2.3
  '@vitejs/plugin-react': 5.1.2
  better-auth: 1.4.18
  dotenv: 17.2.3
  drizzle-kit: 0.31.8
  drizzle-orm: 0.45.1
  lucide-react: 0.563.0
  postcss: 8.5.6
  react: 19.2.4
  react-dom: 19.2.4
  tailwindcss: 4.1.18
  typescript: "5"
  vite: 7.3.1
  zod: 4.3.6
  zustand: 5.0.10

onlyBuiltDependencies:
  - simple-git-hooks
