packages:
  - apps/*
  - packages/*

catalogs:
  dev:
    '@biomejs/biome': 2.3.13
    '@tailwindcss/vite': 4.1.18
    '@tanstack/devtools-vite': 0.5.0
    '@tanstack/react-devtools': 0.9.4
    '@tanstack/react-query-devtools': 5.91.3
    '@tanstack/react-router-devtools': 1.157.18
    '@tanstack/router-plugin': 1.157.18
    '@testing-library/jest-dom': 6.9.1
    '@testing-library/react': 16.3.2
    '@testing-library/user-event': 14.6.1
    '@types/node': 25.1.0
    '@types/pg': 8.16.0
    '@types/react': 19.2.10
    '@types/react-dom': 19.2.3
    '@vitejs/plugin-react': 5.1.2
    '@vitest/coverage-v8': 4.0.18
    drizzle-kit: 0.31.8
    i18next-cli: 1.41.4
    jsdom: 27.4.0
    knip: 5.82.1
    lint-staged: 16.2.7
    postcss: 8.5.6
    simple-git-hooks: 2.13.1
    tailwindcss: 4.1.18
    tsdown: 0.20.1
    tsx: 4.21.0
    turbo: 2.8.1
    typescript: '5'
    vite: 7.3.1
    vitest: 4.0.18
  frontend:
    '@base-ui/react': 1.1.0
    '@hookform/resolvers': 5.2.2
    '@rive-app/react-webgl2': 4.26.2
    '@streamdown/cjk': 1.0.1
    '@streamdown/code': 1.0.1
    '@streamdown/math': 1.0.1
    '@streamdown/mermaid': 1.0.1
    '@tanstack/react-form': 1.28.0
    '@tanstack/react-query': 5.90.20
    '@tanstack/react-router': 1.157.18
    '@xyflow/react': 12.10.0
    ai: 6.0.67
    ansi-to-react: 6.2.6
    class-variance-authority: 0.7.1
    clsx: 2.1.1
    cmdk: 1.1.1
    embla-carousel-react: 8.6.0
    i18next: 25.8.0
    i18next-browser-languagedetector: 8.2.0
    i18next-resources-to-backend: 1.2.1
    input-otp: 1.4.2
    lucide-react: 0.563.0
    media-chrome: 4.17.2
    motion: 12.29.2
    nanoid: 5.1.6
    next-themes: 0.4.6
    react: 19.2.4
    react-dom: 19.2.4
    react-i18next: 16.5.4
    shadcn: 3.8.0
    shiki: 3.22.0
    sonner: 2.0.7
    streamdown: 2.1.0
    tailwind-merge: 3.4.0
    tokenlens: 1.3.1
    tw-animate-css: 1.4.0
    use-stick-to-bottom: 1.1.2
    zustand: 5.0.10
  prod:
    '@fastify/cors': 11.2.0
    '@fastify/helmet': 13.0.2
    '@orpc/client': 1.13.4
    '@orpc/contract': 1.13.4
    '@orpc/openapi': 1.13.4
    '@orpc/server': 1.13.4
    '@orpc/tanstack-query': 1.13.4
    '@orpc/zod': 1.13.4
    '@t3-oss/env-core': 0.13.10
    better-auth: 1.4.18
    dotenv: 17.2.3
    drizzle-orm: 0.45.1
    fastify: 5.7.2
    pg: 8.18.0
    resend: 6.9.1
    zod: 4.3.6

onlyBuiltDependencies:
  - '@swc/core'
  - simple-git-hooks
